document.addEventListener('DOMContentLoaded', () => {
	const { keys, read, write, currentUser, setupShell, showToast } = TravelMate;
	const loginForm = document.querySelector('#login-form');
	const registerForm = document.querySelector('#register-form');
	const profileForm = document.querySelector('#profile-form');
	const showMessage = (selector, message, type = 'error') => { const element = document.querySelector(selector); if (element) { element.className = `notice notice-${type}`; element.textContent = message; } };
	if (loginForm) loginForm.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(loginForm); const email = data.get('email').trim().toLowerCase(); const password = data.get('password'); if (!email || password.length < 6) return showMessage('#login-message', 'Enter a valid email and a password of at least six characters.'); const users = read('travelmate_users', []); const found = users.find((user) => user.email === email && user.password === password); if (!found) return showMessage('#login-message', 'We could not match those details. Try registering a new account.'); const { password: ignored, ...safeUser } = found; write(keys.user, safeUser); window.location.href = 'pages/dashboard.html'; });
	if (registerForm) registerForm.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(registerForm); const name = data.get('name').trim(); const email = data.get('email').trim().toLowerCase(); const password = data.get('password'); const confirm = data.get('confirm'); if (name.length < 2 || !email || password.length < 6) return showMessage('#register-message', 'Complete each field. Passwords must be at least six characters.'); if (password !== confirm) return showMessage('#register-message', 'Passwords do not match.'); const users = read('travelmate_users', []); if (users.some((user) => user.email === email)) return showMessage('#register-message', 'An account with that email already exists.'); const user = { id: TravelMate.uid('user'), name, email, preference: 'Nature & Peace', password }; users.push(user); write('travelmate_users', users); const { password: ignored, ...safeUser } = user; write(keys.user, safeUser); window.location.href = 'dashboard.html'; });
	if (profileForm) { if (!TravelMate.requireUser()) return; const user = setupShell(); profileForm.elements.name.value = user.name || ''; profileForm.elements.address.value = user.address || ''; profileForm.elements.state.value = user.state || ''; profileForm.elements.country.value = user.country || ''; profileForm.elements.email.value = user.email || ''; profileForm.elements.preference.value = user.preference || 'Nature & Peace'; profileForm.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(profileForm); const updated = { ...currentUser(), name: data.get('name').trim(), address: data.get('address').trim(), state: data.get('state'), country: data.get('country'), email: data.get('email').trim().toLowerCase(), preference: data.get('preference') }; if (updated.name.length < 2 || !updated.address || !updated.state || !updated.country || !updated.email || !updated.preference) return showToast('Please complete your profile.'); write(keys.user, updated); const users = read('travelmate_users', []); write('travelmate_users', users.map((item) => item.id === updated.id ? { ...item, ...updated } : item)); setupShell(); showToast('Profile saved.'); }); }
});
