document.addEventListener('DOMContentLoaded', () => {
	if (!TravelMate.requireUser()) return;
	TravelMate.setupShell();
	const form = document.querySelector('#expense-editor'); const list = document.querySelector('#expense-list'); const filter = document.querySelector('#expense-filter'); let expenses = TravelMate.read(TravelMate.keys.expenses); const trips = TravelMate.read(TravelMate.keys.trips);
	const tripName = (id) => trips.find((trip) => trip.id === id)?.destination || 'Unassigned';
	trips.forEach((trip) => { filter.insertAdjacentHTML('beforeend', `<option value="${trip.id}">${trip.destination}</option>`); document.querySelector('#expense-trip').insertAdjacentHTML('beforeend', `<option value="${trip.id}">${trip.destination}</option>`); });
	const render = () => { const selected = filter.value; const shown = selected === 'all' ? expenses : expenses.filter((expense) => expense.tripId === selected); const total = expenses.reduce((sum, expense) => sum + Number(expense.amount), 0); const budget = trips.reduce((sum, trip) => sum + Number(trip.budget), 0); document.querySelector('#expense-summary').innerHTML = `<article class="card stat-card"><span class="stat-label">Recorded spend</span><strong class="stat-value">${TravelMate.formatCurrency(total)}</strong><span class="stat-note">Across all trips</span></article><article class="card stat-card"><span class="stat-label">Total budget</span><strong class="stat-value">${TravelMate.formatCurrency(budget)}</strong><span class="stat-note">${budget ? Math.round(total / budget * 100) : 0}% utilized</span></article><article class="card stat-card"><span class="stat-label">Entries</span><strong class="stat-value">${expenses.length}</strong><span class="stat-note">Every detail counts</span></article><article class="card stat-card"><span class="stat-label">Average entry</span><strong class="stat-value">${TravelMate.formatCurrency(expenses.length ? total / expenses.length : 0)}</strong><span class="stat-note">Per expense record</span></article>`; const categories = {}; expenses.forEach((expense) => { categories[expense.category] = (categories[expense.category] || 0) + Number(expense.amount); }); document.querySelector('#category-summary').innerHTML = Object.keys(categories).length ? Object.entries(categories).sort((a, b) => b[1] - a[1]).map(([category, amount]) => `<div style="margin-bottom:1rem"><div class="section-heading" style="margin-bottom:.35rem"><span><i class="category-dot"></i>${category}</span><strong>${TravelMate.formatCurrency(amount)}</strong></div><div class="progress"><div class="progress-bar" style="width:${total ? amount / total * 100 : 0}%"></div></div></div>`).join('') : '<div class="empty-state">No spending recorded.</div>'; list.innerHTML = shown.length ? shown.sort((a, b) => b.date.localeCompare(a.date)).map((expense) => `<tr><td><strong>${expense.title}</strong></td><td>${expense.category}</td><td>${TravelMate.formatDate(expense.date)}</td><td>${tripName(expense.tripId)}</td><td>${TravelMate.formatCurrency(expense.amount)}</td><td><div class="action-group"><button class="button button-secondary button-small" data-edit="${expense.id}">Edit</button><button class="button button-danger button-small" data-delete="${expense.id}">Delete</button></div></td></tr>`).join('') : '<tr><td colspan="6" class="empty-state">No expenses found.</td></tr>'; };
	form.addEventListener('submit', (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const expense = { id: data.id || TravelMate.uid('expense'), title: data.title.trim(), amount: Number(data.amount), category: data.category, date: data.date, tripId: data.tripId }; if (!expense.title || expense.amount <= 0 || !expense.date || !expense.tripId) return TravelMate.showToast('Complete all expense fields.'); expenses = data.id ? expenses.map((item) => item.id === data.id ? expense : item) : [expense, ...expenses]; TravelMate.write(TravelMate.keys.expenses, expenses); form.reset(); form.elements.id.value = ''; document.querySelector('#expense-form-title').textContent = 'Add expense'; render(); TravelMate.showToast(data.id ? 'Expense updated.' : 'Expense saved.'); });
	form.addEventListener('reset', () => setTimeout(() => { form.elements.id.value = ''; document.querySelector('#expense-form-title').textContent = 'Add expense'; }, 0)); filter.addEventListener('change', render); list.addEventListener('click', (event) => { const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; if (event.target.dataset.edit) { const expense = expenses.find((item) => item.id === id); Object.entries(expense).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value; }); document.querySelector('#expense-form-title').textContent = 'Edit expense'; window.scrollTo({ top: 0, behavior: 'smooth' }); } else if (confirm('Delete this expense?')) { expenses = expenses.filter((item) => item.id !== id); TravelMate.write(TravelMate.keys.expenses, expenses); render(); TravelMate.showToast('Expense deleted.'); } }); render();
});
