document.addEventListener('DOMContentLoaded', () => {
	if (!TravelMate.requireUser()) return;
	TravelMate.setupShell();
	const trips = TravelMate.read(TravelMate.keys.trips); const expenses = TravelMate.read(TravelMate.keys.expenses); const totalSpent = expenses.reduce((sum, expense) => sum + Number(expense.amount), 0); const totalBudget = trips.reduce((sum, trip) => sum + Number(trip.budget), 0); const destinationCounts = trips.reduce((counts, trip) => { counts[trip.destination] = (counts[trip.destination] || 0) + 1; return counts; }, {}); const mostVisited = Object.entries(destinationCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || 'No destinations yet';
	document.querySelector('#report-stats').innerHTML = `<article class="card stat-card"><span class="stat-label">Total trips</span><strong class="stat-value">${trips.length}</strong><span class="stat-note">Your travel archive</span></article><article class="card stat-card"><span class="stat-label">Total expenses</span><strong class="stat-value">${TravelMate.formatCurrency(totalSpent)}</strong><span class="stat-note">Recorded to date</span></article><article class="card stat-card"><span class="stat-label">Budget utilization</span><strong class="stat-value">${totalBudget ? Math.round(totalSpent / totalBudget * 100) : 0}%</strong><span class="stat-note">Across all plans</span></article><article class="card stat-card"><span class="stat-label">Most visited</span><strong class="stat-value" style="font-size:1.2rem">${mostVisited}</strong><span class="stat-note">A place worth returning to</span></article>`;
	const months = []; const now = new Date(); for (let index = 5; index >= 0; index -= 1) { const date = new Date(now.getFullYear(), now.getMonth() - index, 1); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; months.push({ key, label: date.toLocaleDateString('en-US', { month: 'short' }), amount: expenses.filter((expense) => expense.date.startsWith(key)).reduce((sum, expense) => sum + Number(expense.amount), 0) }); } const max = Math.max(...months.map((month) => month.amount), 1); document.querySelector('#monthly-chart').innerHTML = months.map((month) => `<div style="height:${Math.max(month.amount / max * 100, 5)}%"><em>${TravelMate.formatCurrency(month.amount)}</em><span>${month.label}</span></div>`).join('');
	document.querySelector('#budget-report').innerHTML = trips.length ? trips.map((trip) => { const spent = expenses.filter((expense) => expense.tripId === trip.id).reduce((sum, expense) => sum + Number(expense.amount), 0); const percentage = trip.budget ? Math.min(spent / trip.budget * 100, 100) : 0; return `<div style="margin-bottom:1.2rem"><div class="section-heading" style="margin-bottom:.35rem"><span>${trip.destination}</span><strong>${Math.round(percentage)}%</strong></div><div class="progress"><div class="progress-bar" style="width:${percentage}%"></div></div></div>`; }).join('') : '<div class="empty-state">Add a trip to see budget utilization.</div>';
	document.querySelector('#trip-report').innerHTML = trips.length ? trips.map((trip) => { const spent = expenses.filter((expense) => expense.tripId === trip.id).reduce((sum, expense) => sum + Number(expense.amount), 0); const remaining = Number(trip.budget) - spent; const percentage = trip.budget ? Math.round(spent / trip.budget * 100) : 0; return `<tr><td><strong>${trip.destination}</strong></td><td>${TravelMate.formatCurrency(trip.budget)}</td><td>${TravelMate.formatCurrency(spent)}</td><td>${TravelMate.formatCurrency(remaining)}</td><td>${percentage}%</td></tr>`; }).join('') : '<tr><td colspan="5" class="empty-state">No trips to report.</td></tr>';
});
