document.addEventListener('DOMContentLoaded', () => {
	if (!TravelMate.requireUser()) return;
	TravelMate.setupShell();
	const form = document.querySelector('#trip-editor'); const list = document.querySelector('#trip-list'); const search = document.querySelector('#trip-search'); let trips = TravelMate.read(TravelMate.keys.trips);
	const membersField = document.createElement('div'); membersField.className = 'field field-full'; membersField.innerHTML = '<div class="section-heading"><div><label>Trip members</label><p class="muted">Add the name and address of everyone joining this trip.</p></div><button class="button button-secondary button-small" type="button" id="add-trip-member">+ Add member</button></div><div id="trip-members" class="trip-members"></div>'; form.insertBefore(membersField, form.querySelector('.form-actions'));
	const membersList = membersField.querySelector('#trip-members');
	const addMember = (member = {}) => { const row = document.createElement('div'); row.className = 'trip-member-row'; row.innerHTML = `<div class="field"><label>Member name</label><input name="memberName" value="${member.name || ''}" required></div><div class="field"><label>Member address</label><input name="memberAddress" value="${member.address || ''}" required></div><button class="button button-danger button-small remove-trip-member" type="button">Remove</button>`; membersList.append(row); };
	const resetMembers = () => { membersList.innerHTML = ''; addMember(); };
	const getMembers = () => [...membersList.querySelectorAll('.trip-member-row')].map((row) => ({ name: row.querySelector('[name="memberName"]').value.trim(), address: row.querySelector('[name="memberAddress"]').value.trim() }));
	resetMembers(); membersField.querySelector('#add-trip-member').addEventListener('click', () => addMember()); membersList.addEventListener('click', (event) => { if (event.target.classList.contains('remove-trip-member')) { event.target.closest('.trip-member-row').remove(); if (!membersList.children.length) addMember(); } });
	const resetForm = () => { form.reset(); form.elements.id.value = ''; resetMembers(); document.querySelector('#trip-form-title').textContent = 'Plan a new trip'; };
	const render = () => { const query = search.value.toLowerCase(); const filtered = trips.filter((trip) => trip.destination.toLowerCase().includes(query)); document.querySelector('#trip-count').textContent = `${trips.length} saved ${trips.length === 1 ? 'trip' : 'trips'}`; list.innerHTML = filtered.length ? filtered.map((trip) => { const status = TravelMate.statusFor(trip); return `<article class="card trip-card"><div class="section-heading"><div><h3>${trip.destination}</h3><p class="muted">${trip.notes || 'No notes added.'}</p></div><span class="status status-${status.toLowerCase()}">${status}</span></div><div class="trip-meta"><span>${TravelMate.formatDate(trip.startDate)} - ${TravelMate.formatDate(trip.endDate)}</span><span>${TravelMate.formatCurrency(trip.budget)}</span><span>${trip.transportation || 'Transport TBD'}</span></div><div class="action-group"><button class="button button-secondary button-small" data-edit="${trip.id}">Edit</button><button class="button button-danger button-small" data-delete="${trip.id}">Delete</button></div></article>`; }).join('') : '<div class="empty-state">No trips match that search.</div>'; };
	const loadForm = (trip) => { Object.entries(trip).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value; }); membersList.innerHTML = ''; (trip.members || []).forEach((member) => addMember(member)); if (!membersList.children.length) addMember(); document.querySelector('#trip-form-title').textContent = 'Edit trip'; window.scrollTo({ top: 0, behavior: 'smooth' }); };
	form.addEventListener('submit', (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const members = getMembers(); if (data.endDate < data.startDate) return TravelMate.showToast('End date must be after the start date.'); if (!members.length || members.some((member) => !member.name || !member.address)) return TravelMate.showToast('Add a name and address for every trip member.'); const trip = { id: data.id || TravelMate.uid('trip'), destination: data.destination.trim(), startDate: data.startDate, endDate: data.endDate, budget: Number(data.budget), hotel: data.hotel.trim(), transportation: data.transportation.trim(), notes: data.notes.trim(), members }; trips = data.id ? trips.map((item) => item.id === data.id ? trip : item) : [trip, ...trips]; TravelMate.write(TravelMate.keys.trips, trips); resetForm(); render(); TravelMate.showToast(data.id ? 'Trip updated.' : 'Trip saved.'); });
	form.addEventListener('reset', () => setTimeout(resetForm, 0)); search.addEventListener('input', render); list.addEventListener('click', (event) => { const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; if (event.target.dataset.edit) loadForm(trips.find((trip) => trip.id === id)); else if (confirm('Delete this trip and its record?')) { trips = trips.filter((trip) => trip.id !== id); TravelMate.write(TravelMate.keys.trips, trips); render(); TravelMate.showToast('Trip deleted.'); } }); render();
});
